<div class="head_l">
  <div class="head_r">
    <a class="logo fl"><img src="http://trade.davcai.com/df/images/logo.gif" alt="logo" /></a>
    <div class="banner fl"><a target="_blank" href="http://trade.davcai.com/df/notice/6727.html"><img src="http://cms.davcai.com/resources/resources/picture/1/2013/09/01/201309019830125.jpg" alt="banner" /></a></div>
	<div class="service fr">
       <div class="tt"><b><a href="#" onclick="window.open('http://www.53kf.com/company.php?arg=speakeng&style=1','_blank','height=473,width=703,fullscreen=3,top=200,left=200,status=yes,toolbar=no,menubar=no,resizable=no,scrollbars=no,location=no,titlebar=no,fullscreen=no');"><img alt="大V彩焦点图" border="0" src="http://res.davcai.com/resources/resources/picture/1/2012/06/01/2012060114107246.gif" /></a> </b></div>
		 <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2366741343&site=qq&menu=yes" rel="nofollow" >
		 <img border="0" src="http://trade.davcai.com/df/images/qq_button.png" alt="大V彩客服" ></a>
    </div>
  </div>
</div>