<div style="text-align:center; padding-top:5px;">
	ICP证号:京040626 <br/> 
	客服邮箱:<a href="mailto:service@davcai.com" rel="nofollow">service@davcai.com</a>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F33879a81dd67ca240fc52eea6174bd5d' type='text/javascript'%3E%3C/script%3E"));
</script>
</div>
