ALTER TABLE `lt_user`
	ADD COLUMN `headImageURL` VARCHAR(255) NULL DEFAULT NULL AFTER `pid`,
	ADD COLUMN `nickName` VARCHAR(50) NULL AFTER `headImageURL`,
	ADD COLUMN `sinaWeiboUid` VARCHAR(80) NULL DEFAULT NULL AFTER `nickName`,
	ADD COLUMN `sinaWeiboToken` VARCHAR(80) NULL DEFAULT NULL AFTER `sinaWeiboUid`,
	ADD COLUMN `qqConnectUid` VARCHAR(80) NULL DEFAULT NULL AFTER `sinaWeiboToken`,
	ADD COLUMN `qqConnectToken` VARCHAR(80) NULL DEFAULT NULL AFTER `qqConnectUid`,
	ADD COLUMN `weixinUid` VARCHAR(80) NULL DEFAULT NULL AFTER `qqConnectToken`,
	ADD COLUMN `weixinToken` VARCHAR(180) NULL DEFAULT NULL AFTER `weixinUid`,
	ADD COLUMN `alipayUid` VARCHAR(80) NULL DEFAULT NULL AFTER `weixinToken`,
	ADD COLUMN `alipayToken` VARCHAR(80) NULL DEFAULT NULL AFTER `alipayUid`;
